### ISSUE TITLE
MiBox power issue (maybe other devices as well?)

### ISSUE THREAD

**Issue by glassbase** [JeffLIrion/python-androidtv#18]
When I use the HA media_player.turn_off or off button on the card, my MiBox(es) go into some **"deep?"** sleep where they drop off the network (cannot ping, cannot power on via ADB / HA). 

Yet if I use the power button on the remote, the box goes to sleep, but does not drop the network connection and therefore, can be controlled via HA / ADB. 
(I have 4 MiBox and happens for all) 

** does this issue belong here or over at HA github?

**Comment by glassbase** [comment]
It is like a different power function being called with this module / HA vs using power button on remote.

**Comment by glassbase** [comment]
Should it send SLEEP, not POWER?

**Comment by JeffLIrion** [comment]
Give it a try and see using the [`androidtv.adb_command`](https://www.home-assistant.io/components/androidtv#androidtvadb_command) service.

**Comment by glassbase** [comment]
Tested... SLEEP is the way to go for MiBox... not sure about other boxes. 

Goes to sleep, still pingable, still controllable via HA/ADB.

**Comment by JeffLIrion** [comment]
I don't know the best way to implement different turn on/off commands for different devices. The simplest approach might be to add config entries to the HA component. For example, this package uses the command `dumpsys power | grep mWakefulness | grep -q Awake && input keyevent 26` to turn the device off.

**Comment by glassbase** [comment]
Before you did the work to combine the fire tv and android tv, was it set to do SLEEP because I feel like I never had this issue when I was using yours and a1ex4 custom component until moving to the official component

**Comment by JeffLIrion** [comment]
It's always been the power key (26).

**Comment by JeffLIrion** [comment]
Since other users haven't reported this issue, I assume the current command works for most devices. Hard-coding on/off commands for all devices is beyond the scope of this work, so if you want to modify the turn on/off services in Home Assistant then you should add optional configuration entries that allow the user to override the default actions.

**Comment by glassbase** [comment]
I will just use a universal MP and substitute the turn off command for the ADB service with SLEEP

**Comment by JeffLIrion** [comment]
Try this as a custom component. Use `turn_off_command: "input keyevent 223"` in your configuration. 

https://github.com/JeffLIrion/home-assistant/tree/patch-16/homeassistant/components/androidtv

**Comment by glassbase** [comment]
Quick work with this patch... 

I have 1 of 4 boxes that the turn_off_command does not seem to work. But that same box works fine using the adb_command service with SLEEP. Which does not make sense? Anything I can do to troubleshoot?
(I may factory reset the box to see if there is some OS level issues/glitches.)

**Comment by JeffLIrion** [comment]
Sounds like a configuration issue. You need to include `turn_off_command: "input keyevent 223"` for each media player.

**Comment by glassbase** [comment]
I copy and paste the config for each box and just change IP address so I’m good with config I think. I will report back after factory reset

**Comment by JeffLIrion** [comment]
> Quick work with this patch...
> 
> I have 1 of 4 boxes that the turn_off_command does not seem to work (it is like it sends the POWER command anyways since the box drops network). But that same box works fine using the adb_command service with SLEEP (does not drop network). Which does not make sense? Anything I can do to troubleshoot?
> (I may factory reset the box to see if there is some OS level issues/glitches.)

That just doesn't make any sense. If you're using the component I linked above then the `turn_off` command will send the SLEEP key, assuming it's configured correctly. 

 Did you add a `turn_on_command` configuration entry? If so, what was it? 

If you want to debug it, just add a line like `_LOGGER.critical("Sending the command %s", self.turn_off_command)` to the `turn_off` method, before the `self.aftv.adb_shell(...)` line.

**Comment by glassbase** [comment]
I am sorry for rambling on about this issue... I think its just issues with MiBox. MiBox sometimes drops network when using SLEEP / key 223 as well. Yesterday it seemed to only happen sporadically and only on 1 of 4 of my boxes, but today it seems to be all of them are dropping network. 

SLEEP keeps the networking up about 2/3rds of the time. POWER always kills the networking. So there is definitely a benefit to using SLEEP and creating the patch. It is still not fool proof. 

I just discovered the dropping network has lots of people pissed because they cannot Cast to the box if it was off/sleeping (because it drops networking). Just Google "mibox cast sleep", etc and find many posts. Which this does not happen to the Shield (if Shield is sleeping, can still Cast and Shield wakes up), so must be something Xiaomi does to its boxes/firmwares. 

My suggestion is updating the HA docs to mention that the MiBox  drops networking (on power off ) so it cannot be controlled via ADB /HA. 

One more thing - I am going to monitor my boxes when they sleep from screensaver timeout, because I think the networking stays on after that. Will report on this later today or tomorrow.

**Comment by CultusMechanicus** [comment]
This is a bit of a sidetrack, but the MiBox works so much better if you install a wakelock utility to force it to keep the wifi and cpu awake when you press the power button. The device_idle settings seem to be a bit too aggressive somewhere. I'm personally using [Wake Lock V3](https://github.com/d4rken/wakelock-revamp/releases).

**Comment by glassbase** [comment]
@CultusMechanicus thanks, will try that out. That is "on track" to this issue. That might even be good to mention in HA documentation. 👍 

I am checking on my my boxes overnight and the sleep timeout from the screensaver keeps the networking up? So strange Xiaomi.

**Comment by CultusMechanicus** [comment]
To be fair, this may actually not be entirely Xiaomi's fault. Keeping stuff running during sleep on Android is a black art. Just keeping a GPS tracker working on a phone requires about 18 million random permissions/whitelists/sacrifices to dark gods.

**Comment by glassbase** [comment]
I get that with a phone and battery draining but a 24/7 powered streaming device does not have battery lose issues. And considering the Android TV advertise Chromecast included, casting (and networking) should be available during sleep, just the like the Chromecast devices.

**Comment by glassbase** [comment]
I am not going to jump to conclusions **yet** because a true test will be how it works over a few days..., but the Wake Lock app recommended by @CultusMechanicus is working so far. The only downside is that it is not in the TV version of the Play Store and therefore has to be sideloaded.

I originally only tried the wifi toggle in the app, but that did not work. I had to enable both CPU awake and wifi toggles.

I have tried sleeping, waking, multiple times on multiple MiBoxes and the networking stays up. The HDMI CEC still functions as well - powering on and off my TV so it does not break CEC. 

Will report back in a day or two.

**Comment by glassbase** [comment]
Reporting back... Even though I was out of the house over the last few days, I was randomly switching on/off my MiBoxes and to my amazement, I never lost networking/ADB connection. This was while using the default POWER command, not SLEEP. 

I think this solution of using Awake Lock app as suggested by @CultusMechanicus should be put in HA documentation. 

Thanks Jeff for all the work on this component.
