### ISSUE TITLE
Toshiba Fire TV

### ISSUE THREAD

**Issue by jlvandusen** [JeffLIrion/python-androidtv#205]
Support for embedded Fire TV units such as insignia and toshiba where the fire tv version controls the input select etc... its embedded.

Looking for support or insight to control On/Off and Input changes...

**Comment by JeffLIrion** [comment]
I'm not sure exactly what you're asking about. 

This package interacts with Android TV / Fire TV devices via ADB. You can turn the device on/off by sending keyevents like POWER, HOME, SLEEP, etc.; see [here](https://developer.android.com/reference/android/view/KeyEvent) for more info. This is what the `turn_on()` and `turn_off()` functions do. If your device can't be turned on/off via ADB, then that's beyond the scope of this package. 

You can change the HDMI input by sending the ADB commands presented here: https://gist.github.com/mcfrojd/9e6875e1db5c089b1e3ddeb7dba0f304#gistcomment-3493973

This package doesn't currently have a built-in method for determining the current HDMI input; there's already an issue about that: https://github.com/JeffLIrion/python-androidtv/issues/202
