### ISSUE TITLE
I would like to help with adding support for the new Chromecast with Google TV

### ISSUE THREAD

**Issue by mcarter14777** [JeffLIrion/python-androidtv#207]
GET_PROPERTIES  returns mostly values of none. 

I have found that the normal command to get the current app does not work but this command does.
`"dumpsys activity a . | grep -E 'mResumedActivity' | cut -d ' ' -f 8"`
It returns
`adb_response: com.google.android.apps.tv.launcherx/.home.HomeActivity`

I'd love to learn more about adb/linux/python and in the process, I would like to give you a hand with getting this Add-On working with the new chromecast.

Please let me know however I can help!

Thanks for the awesome Add-On. I love using it on my nVidia Shield

**Comment by sacdroid** [comment]
I was able to get it working with following change 

`US-C02CC2ZLMD6R:python-androidtv sachinpatil$ git diff
diff --git a/androidtv/constants.py b/androidtv/constants.py
index a2ddd99..8273d01 100644
--- a/androidtv/constants.py
+++ b/androidtv/constants.py
@@ -29,10 +29,10 @@ CMD_AUDIO_STATE = r"dumpsys audio | grep paused | grep -qv 'Buffer Queue' && ech
 CMD_AWAKE = "dumpsys power | grep mWakefulness | grep -q Awake"
 
 #: Get the current app
-CMD_CURRENT_APP = "CURRENT_APP=$(dumpsys window windows | grep mCurrentFocus) && CURRENT_APP=${CURRENT_APP#*{* * } && CURRENT_APP=${CURRENT_APP%%/*} && echo $CURRENT_APP"
+CMD_CURRENT_APP = "CURRENT_APP=$(dumpsys window windows | grep 'Window #1') && CURRENT_APP=${CURRENT_APP#*{* * } && CURRENT_APP=${CURRENT_APP%%/*} && echo $CURRENT_APP"
 
 #: Launch an app if it is not already the current app
-CMD_LAUNCH_APP = "CURRENT_APP=$(dumpsys window windows | grep mCurrentFocus) && CURRENT_APP=${{CURRENT_APP#*{{* * }} && CURRENT_APP=${{CURRENT_APP%%/*}} && if [ $CURRENT_APP != '{0}' ]; then monkey -p {0} -c " + INTENT_LAUNCH + " --pct-syskeys 0 1; fi"
+CMD_LAUNCH_APP = "CURRENT_APP=$(dumpsys window windows | grep 'Window #1') && CURRENT_APP=${{CURRENT_APP#*{{* * }} && CURRENT_APP=${{CURRENT_APP%%/*}} && if [ $CURRENT_APP != '{0}' ]; then monkey -p {0} -c " + INTENT_LAUNCH + " --pct-syskeys 0 1; fi"
 
 #: Get the state from ``dumpsys media_session``; this assumes that the variable ``CURRENT_APP`` has been defined
 CMD_MEDIA_SESSION_STATE = "dumpsys media_session | grep -A 100 'Sessions Stack' | grep -A 100 $CURRENT_APP | grep -m 1 'state=PlaybackState {'"
US-C02CC2ZLMD6R:python-androidtv sachinpatil$ 
`
Need to find cleaner way to parameterize this.

**Comment by JeffLIrion** [comment]
I had already modified the command used to obtain the current app for Google TV devices, and I just now modified the command that's used to launch apps.  Both of these commands are the same as what @sacdroid posted.  The latest release should support Google TV devices.

**Comment by sacdroid** [comment]
Thanks @JeffLIrion !

**Comment by JeffLIrion** [comment]
Google TV devices should work with HA 0.117. If not, then we can troubleshoot in this issue.

**Comment by JeffLIrion** [comment]
Have there been any issues with Google TV devices in HA 0.117? If not, let's close this issue.

**Comment by mcarter14777** [comment]
@JeffLIrion no real issues. Just some latency when pressing the play/pause, previous, next, and volume controls. Could be something on my end though. Not a huge issue when it comes to automations.

**Comment by JeffLIrion** [comment]
@mcarter14777 the reason for that is explained here: https://www.home-assistant.io/integrations/androidtv/#androidtvlearn_sendevent-for-faster-adb-commands

I'll close this issue.

**Comment by JeffLIrion** [comment]
The command that's used for retrieving the current app doesn't always work, according to this thread: https://community.home-assistant.io/t/new-chromecast-w-android-tv-integration-only-showing-as-off-or-idle/234424/30

Could someone please try this command:

```
CURRENT_APP=$(dumpsys activity a . | grep -E 'mResumedActivity' | cut -d ' ' -f 8) && CURRENT_APP=${CURRENT_APP%%/*} && echo $CURRENT_APP
```

**Comment by JeffLIrion** [comment]
Closed via https://github.com/JeffLIrion/python-androidtv/pull/214
