### ISSUE TITLE
Hulu app ID

### ISSUE THREAD

**Issue by michaelmior** [JeffLIrion/python-androidtv#241]
For me the app ID of Hulu is `com.hulu.livingroomplus`, not `com.hulu.plus`. Would it be possible to have both?

**Comment by JeffLIrion** [comment]
The values in the `APPS` dictionary have to be unique. You could add it and call it something else, like "Hulu (2)." Or just use the `apps` configuration parameter in Home Assistant to override the default "Hulu" app. 

https://github.com/JeffLIrion/python-androidtv/blob/a2a0f33e4091768cf3e7ed30cedbb6f85f308d53/androidtv/constants.py#L396-L482

**Comment by michaelmior** [comment]
I did end up just overriding myself. Thanks for the reply! This has me curious now why Hulu has two different Android TV apps…
