### ISSUE TITLE
Continuous getevent monitoring

### ISSUE THREAD

**Issue by WeekendWarrior1** [JeffLIrion/python-androidtv#252]
I put together this little script: [https://pastebin.com/RJ3J2nb3](https://pastebin.com/RJ3J2nb3), which I use to monitor key presses on my chromecrast with googletv's remote, and forward/trigger Hass actions.

The reasoning behind it is that the TV I have the chromecast plugged into doesn't have HDMI-CEC, but I am able to control it using IR via Hass. The chromecast remote has volume -+ and a source button that do literally nothing on the chromecast device, they are designed 100% to be passed through to the TV using HDMI-CEC.

The flow is:
remote keypress -> adb getevent -> hass action -> IR to TV

After a small discussion here: [https://www.reddit.com/r/homeassistant/comments/o709m7/is_there_a_way_to_use_an_android_tv_controller/h2xrq66/?context=3](https://www.reddit.com/r/homeassistant/comments/o709m7/is_there_a_way_to_use_an_android_tv_controller/h2xrq66/?context=3), user pjrt cleaned up the script and wrote a simple dockerfile: [https://github.com/pjrt/androidtv-homeassistant-input-reader](https://github.com/pjrt/androidtv-homeassistant-input-reader) and confirmed that it worked for them, allowing them control Hass automations with unused remote buttons.

I had intended to turn it into either a HACS or HA addon, but now I'm wondering if this functionality could potentially be added to this library and the core androidtv component.

I see that you already use getevent for the learn_event functionality, but only call it for an 8 second window.
I am unfamiliar with python's async, so, is having a 'thread' constantly listening to 'getevent' and forwarding keypresses possible within the architecture of this library?

**Comment by JeffLIrion** [comment]
Assuming I understand correctly, it currently wouldn't work due to a limitation in the `adb-shell` package (aka, the Python ADB implementation) that this package uses. The limitation is that multiple streams are not supported. What that means is that each ADB command has to finish before the next ADB command is sent. So having an outstanding ADB command wouldn't work. 

If you're interested in adding this functionality to `adb-shell`, here's a comment where I described how I think it could work: https://github.com/JeffLIrion/adb_shell/pull/165#issuecomment-868514906

**Comment by JeffLIrion** [comment]
I added support for multiple streams to the latest `adb-shell` release (0.4.0), so this should be possible. Note that HA doesn't use this version of `adb-shell` yet, I want more feedback and testing before updating the version used by HA. 

However, your use case seems very specific and I don't see a user-friendly, one-size-fits-all way to generalize it. (How could a user trigger different actions for different events beyond what you've setup in your script?) Maybe some functionality could be added to this package, but I think this is too specialized to make it into the HA integration. But if you can do this in a clean way, you're welcome to submit contributions. 

I think you'd be better off going the custom component route. You can grab the `AndroidTV`/`FireTV` object from here and use it however you'd like: https://github.com/home-assistant/core/blob/c5fe01a466edd6b65b353452d1194b4c3121c848/homeassistant/components/androidtv/media_player.py#L261

**Comment by WeekendWarrior1** [comment]
Thanks Jeff, looks great. I will think on if there is an elegant way to integrate this.
