### ISSUE TITLE
Key events different on androidtv and firetv

### ISSUE THREAD

**Issue by TheZoker** [JeffLIrion/python-androidtv#26]
Some key codes are different on androidtv and fire tv. 

For example `Play/Resume` is 85 for androidtv and `179` for fire tv

What is your suggestion here?

Should we maybe create a `ANDROID_TV_KEYS` and one `FIRE_TV_KEYS` array? 

Fire TV key events: https://developer.amazon.com/docs/fire-tv/supporting-controllers-in-web-apps.html

**Comment by JeffLIrion** [comment]
I think 2 dictionaries is a good idea.

**Comment by TheZoker** [comment]
PR: #27
