### ISSUE TITLE
Change scan interval

### ISSUE THREAD

**Issue by benrjunk** [JeffLIrion/python-androidtv#312]
Since 2022.2 with automatic configuration via UI seem to have lost ability to change scan_interval in homeassistant. Would be nice to be able to change this attribute as the default is too long.

**Comment by JeffLIrion** [comment]
This is controlled by Home Assistant, not this library. 

Someone posted an automation in the HA release announcement thread that would trigger updates every 2 seconds. That is the recommended approach.
