### ISSUE TITLE
Android Debug Bridge (AndroidTV) app_id frequently shows "Failed to write while dumping service window: Broken pipe

### ISSUE THREAD

**Issue by jshank** [JeffLIrion/python-androidtv#349]
### The problem

I have an automation (below) that triggers based on the app_Id from the device via Android Debug Bridge. Since Home Assistant 
/2023.10.4, the platform state attributes often responds with:

```
app_id: Failed to write while dumping service window: Broken pipe
app_name: Failed to write while dumping service window: Broken pipe
source: Failed to write while dumping service window: Broken pipe
adb_response: null
```

This causes automations to trigger based on the state change away from the expected values (testing for `com.valvesoftware.steamlink`).

### Additional information

A few other users have reported this via the Home Assistant integrations github - https://github.com/home-assistant/core/issues/104652

**Comment by Andrewdlec** [comment]
Same issue here.

**Comment by fredamn76** [comment]
Same issue here

**Comment by JohannCR** [comment]
Also affected. Any pointers to debug ? some log or other that ould help finding the source of the issue ? Thx
