### ISSUE TITLE
How can I use the play/pause button with androidtv.adb_command service

### ISSUE THREAD

**Issue by marrobHD** [JeffLIrion/python-androidtv#39]
How can I use the play/pause button with androidtv.adb_command service?

**Comment by JeffLIrion** [comment]
You should just use the `media_player.media_play_pause` service. But if you really want to use the `adb_command` service, the command is `input keyevent 85`.

**Comment by marrobHD** [comment]
thanks. How can I use forward and reverse

**Comment by JeffLIrion** [comment]
https://github.com/JeffLIrion/python-androidtv/blob/master/androidtv/constants.py
