### ISSUE TITLE
Proposal: Read known apps from local or remote json file.

### ISSUE THREAD

**Issue by xalexslx** [JeffLIrion/python-androidtv#42]
As the title suggest, I believe reading the known apps titles from a local/remote json file instead of using constants might be an improvement as it may be more maintainable and also auto updated with some custom scripts (parse app store for example). What do you think?

**Comment by JeffLIrion** [comment]
In the Home Assistant component, you can specify app names with the `apps` config entry. Even if the app names were stored in a separate file, the app-specific state detection logic still needs to be implemented in the code. But if you have an idea for how to simplify state detection modifications, I'm open to it.

**Comment by xalexslx** [comment]
Sorry for long time to reply, pretty busy. After looking in the current app state detection, most of them you use the media media_session_state, so probably we can have a json like

```
- packageName: com.netflix.ninja
  name: Netflix
  # valid values might be media_session_state, wake_lock_size or audio_state
  detectionType: media_session_state
  paused: 2
  playing: 3
  # standby is otherwise values
```

**Comment by JeffLIrion** [comment]
That's an interesting idea. 

## Pros

* It allows the user to customize state detection behavior for their device and apps. 
* It wouldn't be necessary to update the package in order to update the state detection. 

## Cons

* It reduces the incentive for users to contribute state detection pull requests, and so users would have to figure out the logic for themselves. 
* I don't know if such a configuration option would get approved for the Home Assistant component. 

I'm open to the idea, and pull requests are always welcome.

**Comment by JeffLIrion** [comment]
I think I'll give this a shot. Here's my current thought on how to implement it. 

1. Create a method called `_custom_state_detection` that will get called before any of the app-specific state detection code. 
2. Add an attribute to the `AndroidTV` and `FireTV` classes called `custom_state_rules`. It will be a dict, and its format will be like this:

```python
{'com.amazon.tv.launcher': ['standby'],
 'com.netflix.ninja': ['media_session_state'],
 'com.hulu.plus': [{'wake_lock_size' : {1: 'playing', 2: 'paused'}}],
 'another.app': ['audio_state'],
 'yet.another.app': ['media_session_state', {'wake_lock_size' : {1: 'playing', 2: 'paused'}}, 'audio_state']}
```

The keys are app IDs, and the values are lists of rules that are evaluated in order by the `_custom_state_detection` method. Valid rules are:

* `'standby'`, `'playing'`, `'paused'`, `'idle'`, or `'off'`= always use the specified state for the state when this app is open
* `'media_session_state'` = try to use the `media_session_state` property to determine the state
* `'audio_state'` = try to use the `audio_state` property to determine the state
* `{'wake_lock_size': {VAL1: STATE1, VAL2: STATE:2, ...}}` = try to look up the state using the `wake_lock_size` property

I think Home Assistant will be able to convert yaml config to a dictionary, so this can be added as a config option for the HA component. 

Any thoughts or suggestions?

**Comment by JeffLIrion** [comment]
You can try it here: https://github.com/JeffLIrion/ha-androidtv/tree/custom_state_detection/custom_components/androidtv

You need all the files in that directory.  *And make sure that you get the files from the `custom_state_detection` branch!*

**Comment by JeffLIrion** [comment]
Closed by https://github.com/JeffLIrion/python-androidtv/pull/53.
