### ISSUE TITLE
State is idle when an app is playing

### ISSUE THREAD

**Issue by Molodax** [JeffLIrion/python-androidtv#6]
I use it with Philips TV 55POS900212 and it partly works: on/off, mute/unmute, change volume and correctly shows which app is running but it doesn’t change idle status to playing when an app is actually playing. I can provide details if it helps to debug it.

**Comment by JeffLIrion** [comment]
Incorrect state detection is a known issue. I think it might need to be done differently depending on the current app. I'm going to leave this up to the community to fix with pull requests. I think the way to figure it out is through trial and error -- for a particular app, check the properties returned by `get_properties()` and see how to use them to determine the state. It might be necessary to add some new properties, as well.

**Comment by Molodax** [comment]
Maybe it would be still interesting for you, I found what was wrong, at least, in y case. I had to change the code as the following:

        # TODO: determine the state differently based on the current app
        if not awake:
            state = STATE_IDLE
        elif wake_lock_size == 2:
            state = STATE_PLAYING
        else:
            state = STATE_PAUSED

So I changed `wake_lock_size` test to **2**. Also I had to remove test with `AUDIO_STATE_CMD` since it doesn't seem to work correctly. Now it correctly detects states of playing and pause with Netflix, YouTube and Plex.
I can provide further details what the android Philips TV returns for different commands in case someone is interested.

**Comment by JeffLIrion** [comment]
Thanks for the info! What would be most helpful is if you could submit a pull request to the [`firetv` branch](https://github.com/JeffLIrion/python-androidtv/tree/firetv). With my Fire TV, I've found that using the `wake_lock_size` is not always reliable. But either way, I think the state should be idle if `awake` is False, as you have above.

**Comment by Molodax** [comment]
I would be happy to contribute and submit the PR, however, my knowledge in this area are too limited :(

**Comment by JeffLIrion** [comment]
I'm gonna close this issue in favor of https://github.com/JeffLIrion/python-androidtv/issues/12. I created a "state-detection" branch, you can try it by running the script (or copy & pasting the commands) that is in the first post of that issue from your `androidtv` package directory.
