### ISSUE TITLE
Want to try

### ISSUE THREAD

**Issue by earth08** [JeffLIrion/python-androidtv#7]
Please start try and error forum / topin in community so that thiscan be discussed,
I want to try
but dont know the configuration and how to install it.
do i need to pip install androitv.py in hass.io installed on raspbianstrech
i want to try androidtv for my Mini M8s2 android box with androidxperiencetv rom 7.1
If i puy platfrom as android tv error platform androidtv not found appears,
but if i put platform as firetv no error, why?
Please guide and start a topic so that we can try.
Thanks

**Comment by JeffLIrion** [comment]
Use the component from this pull request. Documentation is linked in the first post. https://github.com/home-assistant/home-assistant/pull/21674

**Comment by earth08** [comment]
I have used this files
https://github.com/JeffLIrion/python-androidtv/tree/firetv
And the same config as suggested by you, 
But don’t understand, why it’s showing platform: androidtv not found

**Comment by JeffLIrion** [comment]
Put this `androidtv` folder into your `custom_components` folder. 

https://github.com/JeffLIrion/home-assistant/tree/firetv-to-androidtv/homeassistant/components/androidtv
